# build does not work on Java 9 or later as Java 5 is not a valid target

name: Build

on: 
  push:
    branches:
      - '*'
    tags:
      - 'v*'
      - 'website*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  #v3.0.2

    - name: Set up JDK
      uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3  #v3.4.1
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: 'maven'

    - name: Maven version
      run: |
        mkdir -p ./.mvn
        echo '-e -B -DtrimStackTrace=false' > ./.mvn/maven.config
        mvn --version
        mkdir -p target

    - name: Maven build
      run: |
        mvn install site

    - name: Website
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/website') || startsWith(github.ref, 'refs/tags/v'))
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_GH }}
      run: |
        chmod +x ./.github/website.sh
        .github/website.sh
